### ISSUE TITLE
<leader> t for spec files produces wrong rspec command

### ISSUE THREAD

**Issue by KurtRMueller** [janx/vim-rubytest#29]
Say I have a rails model `post.rb` and a spec `post_spec.rb`.

If I input `<leader>T` while the `post_spec.rb` buffer is open, the command is as follows:

```
rspec spec/models/post_spec.rb  -l 16
```

This works just fine.

However, let's say I input `<leader>t` while my cursor is on line 16 of the spec. This is the following command:

```
rspec spec/models/post_spec.rb  -l 16
```

However, the actual command should be:

```
rspec spec/models/post_spec.rb:16
```

I have the current version of rspec installed, 3.4.1. Let me know if you need any other pieces of information.

**Comment by janx** [comment]
Updated the plugin to use new command syntax as default.
