### ISSUE TITLE
Loading test_helper fails when rubytest_cmd is set to use bundle exec

### ISSUE THREAD

**Issue by asedge** [janx/vim-rubytest#32]
The problem is that the "test" directory is not added to my LOAD_PATH when the rubytest_cmd_* does not start with "ruby".

In my vimrc I use bundle exec when running my ruby tests:
```
let g:rubytest_cmd_test = "bundle exec ruby %p"
let g:rubytest_cmd_testcase = "bundle exec ruby %p -n '/%c/'"
```
When I run a single test case I get the following:
```
bundle exec ruby test/controllers/training_controller_test.rb -n /test_get_content_inserts_base_tag_if_none_exists/
test/controllers/training_controller_test.rb:1:in `require': cannot load such file -- test_helper (LoadError)
        from test/controllers/training_controller_test.rb:1:in `<main>'

shell returned 1
```

Changing [this line](https://github.com/janx/vim-rubytest/blob/master/plugin/rubytest.vim#L94) to: `let cmd = substitute(cmd, 'ruby ', 'ruby -Itest ', '')` fixes my issue.  I can submit a PR but wanted to ask for thoughts on a better way to handle this.

**Comment by janx** [comment]
I think you can set:

```
let g:rubytest_cmd_test = "bundle exec ruby -Itest %p"
let g:rubytest_cmd_testcase = "bundle exec ruby -Itest %p -n '/%c/'"
```

**Comment by asedge** [comment]
Yeah, I suppose I could. Is that preferable to the magic built into the plugin that automatically adds `-Itest` to the command?

**Comment by janx** [comment]
Yes if the auto insertion comes with a switch to turn it off.
